# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ping_form.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1117, 820)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.layoutInputs = QtWidgets.QVBoxLayout()
        self.layoutInputs.setObjectName("layoutInputs")
        self.layoutSettingsInput_1 = QtWidgets.QHBoxLayout()
        self.layoutSettingsInput_1.setSpacing(10)
        self.layoutSettingsInput_1.setObjectName("layoutSettingsInput_1")
        self.layoutTargetInput = QtWidgets.QHBoxLayout()
        self.layoutTargetInput.setObjectName("layoutTargetInput")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.layoutTargetInput.addWidget(self.label_2)
        self.lneditTarget = QtWidgets.QLineEdit(self.centralwidget)
        self.lneditTarget.setObjectName("lneditTarget")
        self.layoutTargetInput.addWidget(self.lneditTarget)
        self.layoutSettingsInput_1.addLayout(self.layoutTargetInput)
        self.layoutPktSizeInput = QtWidgets.QHBoxLayout()
        self.layoutPktSizeInput.setObjectName("layoutPktSizeInput")
        self.lbPktSize = QtWidgets.QLabel(self.centralwidget)
        self.lbPktSize.setObjectName("lbPktSize")
        self.layoutPktSizeInput.addWidget(self.lbPktSize)
        self.lneditPktSize = QtWidgets.QLineEdit(self.centralwidget)
        self.lneditPktSize.setObjectName("lneditPktSize")
        self.layoutPktSizeInput.addWidget(self.lneditPktSize)
        self.layoutSettingsInput_1.addLayout(self.layoutPktSizeInput)
        self.layoutTimeoutInput = QtWidgets.QHBoxLayout()
        self.layoutTimeoutInput.setObjectName("layoutTimeoutInput")
        self.lbTimeout = QtWidgets.QLabel(self.centralwidget)
        self.lbTimeout.setObjectName("lbTimeout")
        self.layoutTimeoutInput.addWidget(self.lbTimeout)
        self.lneditTimeout = QtWidgets.QLineEdit(self.centralwidget)
        self.lneditTimeout.setObjectName("lneditTimeout")
        self.layoutTimeoutInput.addWidget(self.lneditTimeout)
        self.layoutSettingsInput_1.addLayout(self.layoutTimeoutInput)
        self.layoutInputs.addLayout(self.layoutSettingsInput_1)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.layoutInputs.addWidget(self.line)
        self.layoutSettingsInput_2 = QtWidgets.QHBoxLayout()
        self.layoutSettingsInput_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.layoutSettingsInput_2.setSpacing(10)
        self.layoutSettingsInput_2.setObjectName("layoutSettingsInput_2")
        self.layoutPingBtn = QtWidgets.QHBoxLayout()
        self.layoutPingBtn.setObjectName("layoutPingBtn")
        self.btnPing = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnPing.sizePolicy().hasHeightForWidth())
        self.btnPing.setSizePolicy(sizePolicy)
        self.btnPing.setMinimumSize(QtCore.QSize(150, 40))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.btnPing.setFont(font)
        self.btnPing.setStyleSheet("")
        self.btnPing.setFlat(False)
        self.btnPing.setObjectName("btnPing")
        self.layoutPingBtn.addWidget(self.btnPing)
        self.layoutSettingsInput_2.addLayout(self.layoutPingBtn)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.layoutSettingsInput_2.addItem(spacerItem)
        self.layoutMaxHopsInput = QtWidgets.QHBoxLayout()
        self.layoutMaxHopsInput.setObjectName("layoutMaxHopsInput")
        self.lbMaxHops = QtWidgets.QLabel(self.centralwidget)
        self.lbMaxHops.setObjectName("lbMaxHops")
        self.layoutMaxHopsInput.addWidget(self.lbMaxHops)
        self.lneditMaxHops = QtWidgets.QLineEdit(self.centralwidget)
        self.lneditMaxHops.setObjectName("lneditMaxHops")
        self.layoutMaxHopsInput.addWidget(self.lneditMaxHops)
        self.layoutSettingsInput_2.addLayout(self.layoutMaxHopsInput)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.layoutSettingsInput_2.addItem(spacerItem1)
        self.layoutPortInput = QtWidgets.QHBoxLayout()
        self.layoutPortInput.setObjectName("layoutPortInput")
        self.lbPort = QtWidgets.QLabel(self.centralwidget)
        self.lbPort.setObjectName("lbPort")
        self.layoutPortInput.addWidget(self.lbPort)
        self.layoutPortSelect = QtWidgets.QVBoxLayout()
        self.layoutPortSelect.setObjectName("layoutPortSelect")
        self.radbtnDefault = QtWidgets.QRadioButton(self.centralwidget)
        self.radbtnDefault.setChecked(True)
        self.radbtnDefault.setObjectName("radbtnDefault")
        self.layoutPortSelect.addWidget(self.radbtnDefault)
        self.radbtnFixed = QtWidgets.QRadioButton(self.centralwidget)
        self.radbtnFixed.setObjectName("radbtnFixed")
        self.layoutPortSelect.addWidget(self.radbtnFixed)
        self.layoutPortInput.addLayout(self.layoutPortSelect)
        self.layoutPortEdit = QtWidgets.QVBoxLayout()
        self.layoutPortEdit.setObjectName("layoutPortEdit")
        self.lneditDefaultPort = QtWidgets.QLineEdit(self.centralwidget)
        self.lneditDefaultPort.setEnabled(False)
        self.lneditDefaultPort.setReadOnly(True)
        self.lneditDefaultPort.setObjectName("lneditDefaultPort")
        self.layoutPortEdit.addWidget(self.lneditDefaultPort)
        self.lneditFixedPort = QtWidgets.QLineEdit(self.centralwidget)
        self.lneditFixedPort.setEnabled(False)
        self.lneditFixedPort.setObjectName("lneditFixedPort")
        self.layoutPortEdit.addWidget(self.lneditFixedPort)
        self.layoutPortInput.addLayout(self.layoutPortEdit)
        self.layoutSettingsInput_2.addLayout(self.layoutPortInput)
        self.layoutInputs.addLayout(self.layoutSettingsInput_2)
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.layoutInputs.addWidget(self.line_2)
        self.verticalLayout_2.addLayout(self.layoutInputs)
        self.tbWidgetRoute = QtWidgets.QTableWidget(self.centralwidget)
        self.tbWidgetRoute.setObjectName("tbWidgetRoute")
        self.tbWidgetRoute.setColumnCount(0)
        self.tbWidgetRoute.setRowCount(0)
        self.verticalLayout_2.addWidget(self.tbWidgetRoute)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOptions = QtWidgets.QAction(MainWindow)
        self.actionOptions.setObjectName("actionOptions")
        self.actionOptions_2 = QtWidgets.QAction(MainWindow)
        self.actionOptions_2.setObjectName("actionOptions_2")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "UDP Ping Plotter"))
        self.label_2.setText(_translate("MainWindow", "Target:"))
        self.lbPktSize.setText(_translate("MainWindow", "Packet Size:"))
        self.lbTimeout.setText(_translate("MainWindow", "Timeout:"))
        self.btnPing.setText(_translate("MainWindow", "Ping !"))
        self.lbMaxHops.setText(_translate("MainWindow", "Max Hops:"))
        self.lbPort.setText(_translate("MainWindow", "Port:"))
        self.radbtnDefault.setText(_translate("MainWindow", "Default"))
        self.radbtnFixed.setText(_translate("MainWindow", "Fixed"))
        self.actionOptions.setText(_translate("MainWindow", "Options"))
        self.actionOptions_2.setText(_translate("MainWindow", "Options"))
