ICMP_TYPE_UNREACHABLE = 3
ICMP_CODE_PORT_UNREACHABLE = 3
ICMP_TYPE_TTL_EXCEEDED = 11
ICMP_CODE_TTL_EXCEEDED_TRANSIT = 0

UDP_PING_PORT_LOWER = 33434
UDP_PING_PORT_HIGHER = 36000

PING_PKT_NUM = 5
PING_PKT_SIZE = 56
PING_PKT_TTL = 128
PING_TIMEOUT = 5

TRACE_MAX_HOPS = 40
TRACE_MAX_PORBES = 5
TRACE_TIMEOUT = 3